== Server administration

=== System requirements

* Architecture: x86-64 (AMD64)
* Operating system: Debian 11
* https://www.postgresql.org/[PostgreSQL] 14.5 or later
* Required to build from source:
** https://golang.org/[Go] 1.19 or later
** goyacc
** https://gcc.gnu.org/[GCC C compiler] 9.3.0 or later

To install goyacc:

[source,bash]
----
go install golang.org/x/tools/cmd/goyacc@master

export PATH=$PATH:$GOPATH/bin
----

=== Server configuration

Metadb makes use of local storage in a "data directory," which is
created using `metadb` with the `init` command.  In this example we
will create the data directory as `data/`:

[source,bash]
----
metadb init -D data
----

This will also create a file `metadb.conf` in the data directory:

[source,toml]
----
[main]
host =
port =
database =
superuser =
superuser_password =
systemuser =
systemuser_password =
sslmode =
----

This file should be edited to add connection parameters, for example:

[source,toml]
----
[main]
host = a.b.c
port = 5432
database = mydb
superuser = postgres
superuser_password = zpreCaWS7S79dt82zgvD
systemuser = metadb
systemuser_password = ZHivGie5juxGJZmTObHU
sslmode = require
----

=== Starting the server

To start the server:

[source,bash]
----
metadb start -D data
----

To connect to the server:

[source,bash]
----
psql -h localhost -p 8440
----

To stop the server:

[source,bash]
----
metadb stop -D data
----

=== Resynchronizing a data source

If a Kafka data stream fails and cannot be resumed, it may be
necessary to re-stream data to Metadb.  For example, a source database
may become unsynchronized with the analytic database, requiring a new
snapshot of the source database to be streamed.  Metadb can accept
re-streamed data in order to resynchronize with the source, using this
procedure:

1. Update the `topics` and `consumergroup` configuration settings for
   the new data stream.
+
[source,sql]
----
ALTER DATA SOURCE example OPTIONS
    (SET topics '^metadb_2.*', SET consumergroup 'metadb_2_1');
----

2. Stop the Metadb server, and then "reset" the analytic database to
   mark current data as old.  This may take some time to run.
+
[source,bash]
----
metadb stop -D data

metadb reset -D data --source example
----

3. Start the Metadb server to begin streaming the data.

4. Once the new data have finished (or nearly finished) re-streaming,
   stop the Metadb server, and "clean" the analytic database to remove
   old data.
+
[source,bash]
----
metadb clean -D data --source example
----
+
Note that the metadb server currently does not give an indication that
it has finished re-streaming, except that running it with `--debug`
will typically show updates slowing down.  (Having the server report
that initial streaming or re-streaming has finished is a planned
feature.)
+
The precise timing of when "metadb clean" is run is not important, but
it must be run to remove redundant data and to complete the
resynchronization process.

5. Start the server.
+
Until a failed stream is re-streamed by following the process above,
the analytic database may continue to be unsynchronized with the
source.
