== Command reference

=== Functions

==== System information

[%header,cols="1,1,3"]
|===
|Name
|Return type
|Description

|`metadb_version()`
|`*text*`
|Metadb version
|===

===== Examples

Show the current Metadb version:

----
SELECT metadb_version();
----

=== Statements

==== ALTER DATA SOURCE

Change the configuration of a data source

[source,subs="verbatim,quotes"]
----
ALTER DATA SOURCE `*_source_name_*`
    OPTIONS ( [ ADD | SET | DROP ] *_option_* ['*_value_*'] [, ... ] )
----

===== Description

ALTER DATA SOURCE changes connection settings for a data source.

===== Parameters

[frame=none,grid=none,cols="1,2"]
|===
|`*_source_name_*`
|The name of an existing data source.

|`OPTIONS ( [ ADD \| SET \| DROP ] *_option_* ['*_value_*'] [, ... ] )`
|Connection settings and other configuration options for the data source.
|===

===== Options

See CREATE DATA SOURCE

===== Examples

Change the consumer group:

----
ALTER DATA SOURCE example OPTIONS (SET consumergroup 'metadb_example_1');
----

==== AUTHORIZE

Enable access to tables generated from an external data source

[source,subs="verbatim,quotes"]
----
AUTHORIZE SELECT
    ON ALL TABLES IN DATA SOURCE `*_source_name_*`
    TO `*_role_specification_*`
----

===== Description

The AUTHORIZE command grants access to tables.  It differs from GRANT
in that the authorization will also apply to tables created at a later
time in the data source.

.Note
****
[.text-center]
AUTHORIZE currently requires restarting the server before it will take
effect.
****

===== Parameters

[frame=none,grid=none,cols="1,2"]
|===
|`*_source_name_*`
|The name of an existing data source.

|`*_role_specification_*`
|An existing role to be granted the authorization.
|===

===== Examples

----
AUTHORIZE SELECT
    ON ALL TABLES IN DATA SOURCE example
    TO beatrice;
----

==== CREATE DATA ORIGIN

Define a new data origin

[source,subs="verbatim,quotes"]
----
CREATE DATA ORIGIN `*_origin_name_*`
----

===== Description

CREATE DATA ORIGIN defines a new origin.

.Note
****
[.text-center]
CREATE DATA ORIGIN currently requires restarting the server before it
will take effect.
****

===== Parameters

[frame=none,grid=none,cols="1,2"]
|===
|`*_origin_name_*`
|A unique name for the data origin to be created.
|===

===== Examples

Create a new origin `test_origin`:

----
CREATE DATA ORIGIN test_origin;
----


==== CREATE DATA SOURCE

Define a new external data source

[source,subs="verbatim,quotes"]
----
CREATE DATA SOURCE `*_source_name_*` TYPE *_source_type_*
    OPTIONS ( *_option_* '*_value_*' [, ... ] )
----

===== Description

CREATE DATA SOURCE defines connection settings for an external data source.

===== Parameters

[frame=none,grid=none,cols="1,2"]
|===
|`*_source_name_*`
|A unique name for the data source to be created.

|`*_source_type_*`
|The type of data source.  The only type currently supported is `kafka`.

|`OPTIONS ( *_option_* '*_value_*' [, ... ] )`
|Connection settings and other configuration options for the data source.
|===

===== Options for data source type "kafka"

[frame=none,grid=none,cols="1,3"]
|===
|`brokers`
|Kafka bootstrap servers (comma-separated list).

|`security`
|Security protocol: `'ssl'` or `'plaintext'`.  The default is `'ssl'`.

|`topics`
|Regular expressions matching Kafka topics to read (comma-separated list).

|`consumergroup`
|Kafka consumer group ID.

|`schemapassfilter`
|Regular expressions matching schema names to accept (comma-separated list).

|`schemastopfilter`
|Regular expressions matching schema names to ignore (comma-separated list), evaluated after `schemapassfilter`.

|`trimschemaprefix`
|Prefix to remove from schema names.

|`addschemaprefix`
|Prefix to add to schema names.

|`module`
|Name of pre-defined configuration.
|===

===== Examples

Create `example` as a `kafka` data source:

----
CREATE DATA SOURCE example TYPE kafka OPTIONS (
    brokers 'kafka:29092',
    topics '^metadb_example_1.*',
    consumergroup 'metadb_example_1_1',
    addschemaprefix 'example_'
);
----

==== CREATE USER

CREATE USER is mostly equivalent to the PostgreSQL CREATE USER
statement.  However it also creates a schema having the same name as
the user, if the schema does not exist, and grants the user privileges
on the schema.  The schema is intended as a workspace for the user.

==== DROP DATA SOURCE

Remove a data source configuration

[source,subs="verbatim,quotes"]
----
DROP DATA SOURCE `*_source_name_*`
----

===== Description

DROP DATA SOURCE removes a data source configuration.

===== Parameters

[frame=none,grid=none,cols="1,2"]
|===
|`*_source_name_*`
|The name of an existing data source.
|===

===== Examples

Drop a data source `example`:

----
DROP DATA SOURCE example;
----

==== LIST

Show the value of a system variable

[source,subs="verbatim,quotes"]
----
LIST `*_name_*`
----

===== Description

LIST shows the current setting of various system configurations and
other variables.

===== Parameters

[frame=none,grid=none,cols="1,3,8"]
|===
|`*_name_*`
|
|

|
|`authorizations`
|Authorized users.

|
|`data_origins`
|Configured data origins.

|
|`data_sources`
|Configured data sources.

|
|`status`
|Current status of system components.
|===

===== Examples

----
LIST status;
----
