== External projects

=== FOLIO

When creating a FOLIO data source, use the `module 'folio'` option,
and set `trimschemaprefix` to remove the tenant from schema names and
`addschemaprefix` to add a `folio_` prefix to the schema names.  For
example:

----
CREATE DATA SOURCE folio TYPE kafka OPTIONS (
    module 'folio',
    trimschemaprefix 'tenantname_',
    addschemaprefix 'folio_',
    brokers 'kafka:29092',
    topics '^metadb_example_1.*',
    consumergroup 'metadb_example_1_1'
);
----

It is recommended to use a separate Kafka cluster, rather than the
FOLIO Kafka instance, until one has experience with administration of
Kafka.

In the Debezium PostgreSQL connector configuration, the following
exclusions are suggested:

----
"schema.exclude.list": "public,.*_mod_login,.*_mod_pubsub,.*pubsub_config,supertenant_mod_.*,.*_mod_kb_ebsco_java,.*_mod_data_export_spring"
----
----
"table.exclude.list": ".*_mod_agreements.alternate_resource_name,.*_mod_service_interaction.dashboard_access,.*_mod_agreements.availability_constraint,.*_mod_agreements\\.package_description_url,.*_mod_agreements\\.content_type,.*_mod_agreements\\.entitlement_tag,.*_mod_agreements\\.erm_resource_tag,.*_mod_agreements\\.string_template,.*_mod_agreements\\.string_template_scopes,.*_mod_agreements\\.templated_url,.*_mod_oai_pmh\\.instances,.*_mod_remote_storage\\.original_locations,.*_mod_remote_storage\\.item_notes,.*app_setting,.*alternate_name,.*databasechangelog,.*databasechangeloglock,.*directory_entry_tag,.*license_document_attachment,.*license_supp_doc,.*license_tag,.*log_entry_additional_info,.*subscription_agreement_supp_doc,.*subscription_agreement_document_attachment,.*subscription_agreement_ext_lic_doc,.*subscription_agreement_tag,.*tenant_changelog,.*tenant_changelog_lock,.*marc_indexers.*,.*rmb_internal.*,.*rmb_job.*,.*_mod_agreements\\.match_key,.*system_changelog"
----

=== ReShare

Before defining a ReShare data source, create a data origin for each
consortial tenant.  For example:

----
CREATE DATA ORIGIN tenant1;

CREATE DATA ORIGIN tenant2;

CREATE DATA ORIGIN tenant3;
----

Then use the `module 'reshare'` option when creating the data source,
and set `addschemaprefix` to add a `reshare_` prefix to the schema
names:

----
CREATE DATA SOURCE reshare TYPE kafka OPTIONS (
    module 'reshare',
    addschemaprefix 'reshare_',
    brokers 'kafka:29092',
    topics '^metadb_example_1.*',
    consumergroup 'metadb_example_1_1'
);
----

Note that the order of commands is important: The initial set of data
origins should be created before the data source is created so that
schema names of incoming data will be processed correctly.  Later,
whenever a new consortial tenant is to be added, it should be defined
in Metadb using `CREATE DATA ORIGIN` before the tenant is added to
ReShare.

In the Debezium PostgreSQL connector configuration, it is suggested
that credentials (`.+mod_login`), the public schema, the Okapi
supertenant (`supertenant_mod_.+`), and mod-pubsub data
(`pubsub_config,.+_mod_pubsub`) be excluded using the
`schema.exclude.list` setting.
