== Reference

=== Data type conversion

When reading data from a data source, Metadb will automatically adjust column
data types on the fly in a number of cases:

* A data type in the source has changed in a way that cannot be applied safely
  by Metadb without more information.

* A data type in the source has changed to a type that is not supported by
  Metadb.

* A data type in the source can be converted safely to a type that is more
  performant.

Each type conversion is applied in one of two ways: either by the stream
processor converting a record-at-a-time, or later by "inferring" types from
previously updated data.

==== Record-at-a-time

This table summarizes conversions that are performed a record-at-a-time by the
stream processor:

[width=80%]
[%header,cols="2,^1,^1,^1,^1"]
|===
|*Data type conversions*
^|*To numeric*
^|*To uuid*
^|*To jsonb*
^|*To text*

|From boolean
|
|
|
|✅

|From smallint
|✅
|
|
|✅

|From integer
|✅
|
|
|✅

|From bigint
|✅
|
|
|✅

|From real
|✅
|
|
|✅

|From double precision
|✅
|
|
|✅

|From numeric
|
|
|
|✅

|From date
|
|
|
|✅

|From time
|
|
|
|✅

|From time with timezone
|
|
|
|✅

|From timestamp
|
|
|
|✅

|From timestamp with timezone
|
|
|
|✅

|From uuid
|
|
|
|✅

|From json
|
|
|✅
|✅

|From jsonb
|
|
|
|✅
|===

==== Inferred from data

At present the only inferred type is `uuid`:

[width=80%]
[%header,cols="2,^1,^1,^1,^1"]
|===
|*Data type conversions*
^|*To numeric*
^|*To uuid*
^|*To jsonb*
^|*To text*

|From text/varchar
|
|✅
|
|
|===

Types also can be set manually via the `ALTER TABLE` command.

=== Functions

==== System information

[%header,cols="1,2l,2"]
|===
|Name
|Return type
|Description

|`mdblog(interval)`
|table (
    log_time timestamptz(3),
    error_severity text,
    message text
)
|Returns recent log messages during the specified interval, or during the past 24 hours if no interval is given

|`mdbversion()`
|text
|Returns the Metadb version

|`ps()`
|table (
    dbname text,
    username text,
    state text,
    realtime text,
    query text
)
|Returns the status and elapsed running time of current query processes
|===

[discrete]
===== Examples

Show log messages from the past hour, and from the past 24 hours:

----
SELECT * FROM mdblog('1 hour');
----
----
SELECT * FROM mdblog();
----

Show the current Metadb version:

----
SELECT mdbversion();
----

=== System tables

==== metadb.base_table

[.aqua-background]#Metadb 1.2#

The table `metadb.base_table` stores information about tables that are
extracted from data sources or are transformed from those tables.

[%header,cols="1,1l,3"]
|===
|Column name
|Column type
|Description

|`schema_name`
|varchar(63)
|The base table schema name

|`table_name`
|varchar(63)
|The base table name

|`source_name`
|varchar(63)
|Name of the data source the table is extracted from

|`transformed`
|boolean
|True if the table is transformed from another table

|`parent_schema_name`
|varchar(63)
|Schema name of the parent table, if this is a transformed table

|`parent_table_name`
|varchar(63)
|Table name of the parent table, if this is a transformed table
|===

==== metadb.log

The table `metadb.log` stores logging information for the system.

[%header,cols="1l,1l,3"]
|===
|Column name
|Column type
|Description

|log_time
|timestamptz(3)
|Timestamp when the log entry was written

|error_severity
|text
|Logging level: (from least to most severe) INFO, WARNING, ERROR, FATAL

|message
|text
|The log message
|===

==== metadb.table_update

[.aqua-background]#Metadb 1.2#

The table `metadb.table_update` stores information about the updating of
certain tables.

[%header,cols="1,1l,3"]
|===
|Column name
|Column type
|Description

|`schema_name`
|varchar(63)
|Schema name of the updated table

|`table_name`
|varchar(63)
|Table name of the updated table

|`last_update`
|timestamptz
|Timestamp when the table was last updated successfully

|`elapsed_real_time`
|real
|Wall-clock time in seconds of the last completed update process
|===

=== External SQL directives

Metadb allows scheduling external SQL files to run on a regular
basis. At present, the location and frequency of SQL files to run is
hardcoded based the `module` setting that is specified when a data
source is configured (see below). If this is set to either `folio` or
`reshare`, it enables the external SQL from the appropriate known
location.  A relatively high priority feature would be to add
configuration options for this facility, including the Git repository,
tag, path, etc., and time of day and frequency when the SQL should
run.  There is https://github.com/metadb-project/metadb/issues/43[a
placeholder issue for this job-scheduler facility].

Each SQL statement should be separated from others by an empty line, and any
tables created should not specify a schema name.

Comment lines beginning with `--metadb:` are used for special directives; each
directive should be on a separate line.

It is suggested that each SQL file begin with a `--metadb:table` directive,
followed by an empty line, for example:

----
--metadb:table library_patrons

DROP TABLE IF EXISTS library_patrons;

CREATE TABLE library_patrons AS
SELECT . . . ;
----

==== --metadb:table

The `--metadb:table` directive declares that the SQL file updates a
specific table.  This allows Metadb to report on the status of the
table by maintaining the the `metadb.table_update` table described
below.  The directive takes the form:

----
--metadb:table <table>
----

The specified table should not contain a schema name.

For example:

----
--metadb:table user_group
----

=== Statements

Metadb extends SQL with statements for configuring and administering the
server.  These statements are only available when connecting to the Metadb
server (not the PostgreSQL server for the underlying database).

==== ALTER DATA SOURCE

Change the configuration of a data source

[source,subs="verbatim,quotes"]
----
ALTER DATA SOURCE `*_source_name_*`
    OPTIONS ( [ ADD | SET | DROP ] *_option_* ['*_value_*'] [, ... ] )
----

[discrete]
===== Description

ALTER DATA SOURCE changes connection settings for a data source.

.Note
****
[.text-center]
ALTER DATA SOURCE currently requires restarting the server before it
will take effect.
****

[discrete]
===== Parameters

[frame=none,grid=none,cols="1,2"]
|===
|`*_source_name_*`
|The name of an existing data source.

|`OPTIONS ( [ ADD \| SET \| DROP ] *_option_* ['*_value_*'] [, ... ] )`
|Connection settings and other configuration options for the data source.
|===

[discrete]
===== Options

See CREATE DATA SOURCE

[discrete]
===== Examples

Change the consumer group:

----
ALTER DATA SOURCE sensor OPTIONS (SET consumergroup 'metadb_sensor_1');
----

==== ALTER TABLE

[.aqua-background]#Metadb 1.2#

Change a table definition. This is essentially the same as ALTER TABLE
in the underlying PostgreSQL database, but performs additional checks
and should be used instead of the lower-level equivalent.

[source,subs="verbatim,quotes"]
----
ALTER TABLE `*_table_name_*`
    ALTER COLUMN `*_column_name_*` TYPE `*_data_type_*`
----

[discrete]
===== Description

ALTER TABLE changes the definition of a table that is extracted from a data
source.

[discrete]
===== Parameters

[frame=none,grid=none,cols="1,2"]
|===
|`*_table_name_*`
|Schema-qualified name of a main table.

|`*_column_name_*`
|Name of a column to alter.

|`*_data_type_*`
|The new data type of the column.  The only type currently supported is `uuid`.
|===

[discrete]
===== Examples

Change a column type to `uuid`:

----
ALTER TABLE library.patron__ ALTER COLUMN patrongroup_id TYPE uuid;
----

==== AUTHORIZE

Enable access to tables generated from an external data source

[source,subs="verbatim,quotes"]
----
AUTHORIZE SELECT
    ON ALL TABLES IN DATA SOURCE `*_source_name_*`
    TO `*_role_specification_*`
----

[discrete]
===== Description

The AUTHORIZE command grants access to tables.  It differs from GRANT in that
the authorization will also apply to tables created at a later time in the data
source.

.Note
****
[.text-center]
AUTHORIZE currently requires restarting the server before it will take
effect.
****

[discrete]
===== Parameters

[frame=none,grid=none,cols="1,2"]
|===
|`*_source_name_*`
|The name of an existing data source.

|`*_role_specification_*`
|An existing role to be granted the authorization.
|===

[discrete]
===== Examples

----
AUTHORIZE SELECT
    ON ALL TABLES IN DATA SOURCE sensor
    TO beatrice;
----


==== CREATE DATA ORIGIN

Define a new data origin

[source,subs="verbatim,quotes"]
----
CREATE DATA ORIGIN `*_origin_name_*`
----

[discrete]
===== Description

CREATE DATA ORIGIN defines a new origin. Data origins form essentially
a controlled vocabulary for the `__origin` column in tables. They are
used primarily when using a ReShare data source to indicate which
tenant in a consortium a given row was taken from.

(When using Metadb
for FOLIO, each tenant’s data goes into a separate database; but when
using it for ReShare, all the tenants of a consortium go into a single
shared database. ReShare internally uses FOLIO-style tenants to
represent the tenants in a consortium, and Metadb combines the tables
from all the tenants into a single table and fills in `__origin` to
tell users which tenant a record belongs to.)


.Note
****
[.text-center]
CREATE DATA ORIGIN currently requires restarting the server before it will take
effect.
****

[discrete]
===== Parameters

[frame=none,grid=none,cols="1,2"]
|===
|`*_origin_name_*`
|A unique name for the data origin to be created.
|===

[discrete]
===== Examples

Create a new origin `test_origin`:

----
CREATE DATA ORIGIN test_origin;
----


==== CREATE DATA SOURCE

Define a new external data source

[source,subs="verbatim,quotes"]
----
CREATE DATA SOURCE `*_source_name_*` TYPE *_source_type_*
    OPTIONS ( *_option_* '*_value_*' [, ... ] )
----

[discrete]
===== Description

CREATE DATA SOURCE defines connection settings for an external data source.

The new data source starts out in synchronizing mode, which pauses periodic
transforms and running external SQL.  When the initial snapshot has finished
streaming, the message "source snapshot complete (deadline exceeded)" will be
written to the log.  To complete the synchronization, the Metadb server should
be stopped in order to run `metadb endsync`, and after the "endsync" has
completed, the Metadb server can be started again.

(The "deadline exceeded" message here refers to a timeout when waiting
for further change events. So it is communicating that the update has
completed, not that it has been abandoned due to running out of
allocated time.)

[discrete]
===== Parameters

[frame=none,grid=none,cols="1,2"]
|===
|`*_source_name_*`
|A unique name for the data source to be created.

|`*_source_type_*`
|The type of data source.  The only type currently supported is `kafka`.

|`OPTIONS ( *_option_* '*_value_*' [, ... ] )`
|Connection settings and other configuration options for the data source.
|===

[discrete]
===== Options for data source type "kafka"

[frame=none,grid=none,cols="1,3"]
|===
|`brokers`
|Kafka bootstrap servers (comma-separated list).

|`security`
|Security protocol: `'ssl'` or `'plaintext'`.  The default is `'ssl'`.

|`topics`
|Regular expressions matching Kafka topics to read (comma-separated list).

|`consumergroup`
|Kafka consumer group ID.

|`schemapassfilter`
|Regular expressions matching schema names to accept (comma-separated list).

|`schemastopfilter`
|Regular expressions matching schema names to ignore (comma-separated list).

|`tablestopfilter`
|Regular expressions matching table names to ignore (comma-separated list).

|`trimschemaprefix`
|Prefix to remove from schema names.

|`addschemaprefix`
|Prefix to add to schema names.

|`module`
|Name of pre-defined configuration.
|===

[discrete]
===== Examples

Create `sensor` as a `kafka` data source:

----
CREATE DATA SOURCE sensor TYPE kafka OPTIONS (
    brokers 'kafka:29092',
    topics '^metadb_sensor_1\.',
    consumergroup 'metadb_sensor_1_1',
    addschemaprefix 'sensor_',
    tablestopfilter '^testing\.air_temp$,^testing\.air_temp_avg$'
);
----

==== CREATE USER

Define a new database user

[source,subs="verbatim,quotes"]
----
CREATE USER `*_user_name_*` WITH *_option_* '*_value_*' [, ... ]
----

[discrete]
===== Description

CREATE USER defines a new database user that will be managed by Metadb.  It
also creates a schema having the same name as the user, if the schema does not
exist, and grants the user privileges on the schema.  The schema is intended as
a workspace for the user.


[discrete]
===== Parameters

[frame=none,grid=none,cols="1,2"]
|===
|`*_user_name_*`
|The name of the new user.

|`WITH ( *_option_* '*_value_*' [, ... ] )`
|Configuration options for the new user.
|===

[discrete]
===== Options

[frame=none,grid=none,cols="1,3"]
|===
|`password`
|Sets the user's password.  (Required)

|`comment`
|Stores a comment about the user, e.g. the user's real name.  The comment can be viewed in psql using the `\du+` command, or in other user interfaces.
|===

[discrete]
===== Examples

Create a user `wegg`:

----
CREATE USER wegg WITH PASSWORD 'LZn2DCajcNHpGR3ZXWHD', COMMENT 'Silas Wegg';
----


==== DROP DATA SOURCE

Remove a data source configuration

[source,subs="verbatim,quotes"]
----
DROP DATA SOURCE `*_source_name_*`
----

[discrete]
===== Description

DROP DATA SOURCE removes a data source configuration.

[discrete]
===== Parameters

[frame=none,grid=none,cols="1,2"]
|===
|`*_source_name_*`
|The name of an existing data source.
|===

[discrete]
===== Examples

Drop a data source `sensor`:

----
DROP DATA SOURCE sensor;
----

==== LIST

Show the value of a system variable

[source,subs="verbatim,quotes"]
----
LIST `*_name_*`
----

[discrete]
===== Description

LIST shows the current setting of various system configurations and other
variables.

[discrete]
===== Parameters

[frame=none,grid=none,cols="1,3,8"]
|===
|`*_name_*`
|
|

|
|`authorizations`
|Authorized users.

|
|`data_origins`
|Configured data origins.

|
|`data_sources`
|Configured data sources.

|
|`status`
|Current status of system components.
|===

[discrete]
===== Examples

----
LIST status;
----

