== Tutorial

This is an introduction to using Metadb.  We assume familiarity with
databases and the basics of SQL.

=== Getting started

Metadb extends PostgreSQL with features to support analytics such as
streaming data sources, data model transforms, and historical data.
The data contained in the Metadb database originally come from another
place: a *data source* such as a transaction-processing database.
Metadb updates its database continuously based on changes in a data
source.

=== Main tables

Tables generated by Metadb have at least these metadata columns, with
names that begin with two underscores:

* `__id` is a surrogate key that identifies a row in the table.

* `__start` is the date and time when the row of data was generated.

* `__end` is the date and time when the row of data became no longer
  current, or `9999-12-31 00:00:00+00` if the row is still current.

* `__current` is a Boolean value that indicates whether the row
  is current.

* `\__source` identifies the data source.  The value of `__source` is
  the same for all rows that have been read from the same data source.

* `\__origin` is an optional identifier used to group related data
  from one or more data sources.  For example, Metadb can combine data
  from similar source tables into a single table in the analytic
  database, and stores an identifier in `__origin` to record where the
  data came from.

A *main table* in Metadb has two underscores at the end of its name
(e.g., `patrongroup__`), and it contains both the current state and
the history of all previous states provided by the data source.  For
instance, consider a main table that stores categories of patrons in a
library:

[source]
----
SELECT __start, __end, __current, id, groupname, description FROM library.patrongroup__;
----

[%header,cols="4m,4m,2m,>1m,2m,4m"]
|===
^|`*__start*`
^|`*__end*`
^|`*__current*`
^|`*id*`
^|`*groupname*`
^|`*description*`

|2022-04-17 21:42:25-00
|2022-04-18 19:27:18-00
|FALSE
|15
|undergrad
|Student

|2022-04-18 19:27:18-00
|9999-12-31 00:00:00+00
|TRUE
|15
|undergrad
|Undergraduate Student

|2022-04-17 21:42:25-00
|9999-12-31 00:00:00+00
|TRUE
|10
|graduate
|Graduate Student

|2022-04-17 21:52:53-00
|9999-12-31 00:00:00+00
|TRUE
|9
|faculty
|Faculty Member

|2022-04-17 21:52:53-00
|9999-12-31 00:00:00+00
|TRUE
|12
|staff
|Staff Member
|===

In this example, the "undergrad" group with `id` = 15 has two rows
because it was modified on `2022-04-18 19:27:18-00`, changing
`description` from `'Student'` to `'Undergraduate Student'`.

=== Current tables

It is often desirable to limit a query to retrieving only current
records.  This can be done by filtering on `__current` = `TRUE`, for
example:

[source]
----
SELECT id, groupname, description FROM library.patrongroup__ WHERE __current;
----

For convenience, since this filter is so often used, Metadb provides
access to a *current table* which contains only current records.
Every main table has a corresponding current table, which shares the
same name but without the two underscores at the end.  For instance,
the following query is equivalent to the example above:

[source]
----
SELECT id, groupname, description FROM library.patrongroup;
----

A current table reflects the current state of each row in the data
source, as of the last time the row was updated.

To take another example:

[source]
----
SELECT __id, __start, __source, __origin, id, groupname, description FROM library.patrongroup;
----

[%header,cols=">1m,4m,2m,2m,>1m,2m,4m"]
|===
^|`*__id*`
^|`*__start*`
^|`*__source*`
^|`*__origin*`
^|`*id*`
^|`*groupname*`
^|`*description*`

|8
|2022-04-18 19:27:18-00
|library
|west
|15
|undergrad
|Undergraduate Student

|4
|2022-04-17 17:42:25-00
|library
|east
|10
|graduate
|Graduate Student

|5
|2022-04-17 17:52:53-00
|library
|east
|9
|faculty
|Faculty Member

|6
|2022-04-17 17:52:53-00
|library
|east
|12
|staff
|Staff Member
|===

Note that there is a distinction between the `\__id` and `id` columns.
The `__id` column is a key defined by Metadb to identify each row
uniquely; it is present in all tables generated by Metadb.  In
contrast, the `id` column only happens to be present in this sample
table and has been provided by the data source; it may or may not be a
key, and its name, content, or significance may change if schema
changes are made in the data source.

=== Transformed tables

Metadb applies transformations to some kinds of data, which results in
additional tables being created.  One category of data that are
transformed in this way is JSON objects.  Suppose that our
`patrongroup` current table contains the `groupname` and `description`
data in JSON fields, for example:

[source]
----
SELECT __id, __start, id, jsondata FROM library.patrongroup;
----

[%header,cols=">1m,4m,>1m,8m"]
|===
^|`*__id*`
^|`*__start*`
^|`*id*`
^|`*jsondata*`

|8
|2022-04-18 19:27:18-00
|15
a|
----
{
    "groupname": "undergrad",
    "description": "Undergraduate Student"
}
----

|4
|2022-04-17 17:42:25-00
|10
a|
----
{
    "groupname": "graduate",
    "description": "Graduate Student"
}
----

|5
|2022-04-17 17:52:53-00
|9
a|
----
{
    "groupname": "faculty",
    "description": "Faculty Member"
}
----

|6
|2022-04-17 17:52:53-00
|12
a|
----
{
    "groupname": "staff",
    "description": "Staff Member"
}
----
|===

Metadb will generate a *transformed table* called `patrongroup__t`
with JSON fields extracted into columns.

[source]
----
SELECT __id, __start, id, groupname, description FROM library.patrongroup__t;
----

[%header,cols=">1m,4m,>1m,2m,6m"]
|===
^|`*__id*`
^|`*__start*`
^|`*id*`
^|`*groupname*`
^|`*description*`

|2
|2022-04-18 19:27:18-00
|15
|undergrad
|Undergraduate Student

|5
|2022-04-17 17:42:25-00
|10
|graduate
|Graduate Student

|4
|2022-04-17 17:52:53-00
|9
|faculty
|Faculty Member

|6
|2022-04-17 17:52:53-00
|12
|staff
|Staff Member
|===

Main tables are also transformed in the same way.

Note that JSON data are treated as "schemaless," and fields are
inferred from their presence in the data rather than read from a JSON
schema.  As a result, a column is only created from a JSON field if
the field is present in at least one JSON record.

=== Workspaces

Metadb creates a schema name space for each user to serve as an
individual workspace.  The schema has the same name as the user name,
and it can be used as an area within the database for creating
tables.  This can be useful for saving the results of queries or
importing external data sets.

To use this workspace, it is not necessary to specify the schema name;
it will be selected by default if no schema is specified.

For example:

[source]
----
CREATE TABLE westgroup AS SELECT * FROM library.patrongroup WHERE __origin = 'west';
----

[source]
----
SELECT * FROM westgroup;
----

=== System log

Metadb reports errors and other information in a logging table called
`metadb.log`.  For instance to view all log messages from January,
2023:

----
SELECT *
    FROM metadb.log
    WHERE log_time >= '2023-01-01' AND log_time < '2023-02-01'
    ORDER BY log_time;
----
