// Code generated by goyacc -l -o gram.go gram.y. DO NOT EDIT.
package parser

import __yyfmt__ "fmt"

import (
	"github.com/metadb-project/metadb/cmd/metadb/ast"
)

type yySymType struct {
	yys               int
	str               string
	funcparamtypelist []string
	optlist           []ast.Option
	node              ast.Node
	pass              bool
}

const DEREGISTER = 57346
const FUNCTION = 57347
const REGISTER = 57348
const SELECT = 57349
const SYSTEM = 57350
const TABLE = 57351
const CONSISTENCY = 57352
const CREATE = 57353
const GRANT = 57354
const REVOKE = 57355
const ACCESS = 57356
const ALTER = 57357
const DATA = 57358
const SOURCE = 57359
const ORIGIN = 57360
const OPTIONS = 57361
const USER = 57362
const AUTHORIZE = 57363
const DEAUTHORIZE = 57364
const ON = 57365
const ALL = 57366
const TABLES = 57367
const IN = 57368
const TO = 57369
const WITH = 57370
const MAPPING = 57371
const LIST = 57372
const REFRESH = 57373
const INFERRED = 57374
const COLUMN = 57375
const TYPES = 57376
const TYPE = 57377
const TRUE = 57378
const FALSE = 57379
const VERIFY = 57380
const FOR = 57381
const FROM = 57382
const PATH = 57383
const SCHEMA = 57384
const VERSION = 57385
const ADD = 57386
const SET = 57387
const DROP = 57388
const IDENT = 57389
const NUMBER = 57390
const SLITERAL = 57391

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"DEREGISTER",
	"FUNCTION",
	"REGISTER",
	"SELECT",
	"SYSTEM",
	"TABLE",
	"CONSISTENCY",
	"CREATE",
	"GRANT",
	"REVOKE",
	"ACCESS",
	"ALTER",
	"DATA",
	"SOURCE",
	"ORIGIN",
	"OPTIONS",
	"USER",
	"AUTHORIZE",
	"DEAUTHORIZE",
	"ON",
	"ALL",
	"TABLES",
	"IN",
	"TO",
	"WITH",
	"MAPPING",
	"LIST",
	"REFRESH",
	"INFERRED",
	"COLUMN",
	"TYPES",
	"TYPE",
	"TRUE",
	"FALSE",
	"VERIFY",
	"FOR",
	"FROM",
	"PATH",
	"SCHEMA",
	"VERSION",
	"ADD",
	"SET",
	"DROP",
	"IDENT",
	"NUMBER",
	"SLITERAL",
	"'='",
	"';'",
	"'('",
	"')'",
	"','",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

var yyExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 229

var yyAct = [...]uint8{
	107, 161, 106, 150, 104, 160, 105, 198, 127, 185,
	182, 128, 168, 33, 142, 32, 29, 181, 182, 56,
	12, 34, 35, 54, 15, 171, 172, 139, 56, 165,
	30, 31, 54, 126, 109, 134, 127, 53, 159, 36,
	37, 62, 216, 213, 66, 212, 68, 38, 210, 209,
	72, 73, 204, 202, 27, 17, 28, 183, 179, 167,
	79, 163, 81, 157, 147, 133, 84, 130, 87, 123,
	89, 56, 153, 152, 151, 54, 114, 110, 103, 215,
	93, 102, 92, 88, 108, 78, 76, 211, 129, 131,
	63, 56, 65, 206, 39, 54, 118, 119, 40, 121,
	122, 80, 124, 201, 56, 197, 184, 141, 54, 125,
	120, 64, 132, 57, 148, 101, 100, 187, 137, 111,
	41, 140, 77, 59, 61, 82, 214, 200, 194, 180,
	138, 117, 91, 136, 146, 60, 135, 154, 116, 158,
	162, 99, 164, 162, 115, 98, 169, 90, 166, 170,
	75, 74, 71, 96, 173, 174, 175, 95, 70, 46,
	97, 83, 50, 45, 49, 144, 176, 178, 113, 42,
	43, 177, 94, 186, 69, 154, 188, 44, 191, 192,
	67, 193, 156, 162, 195, 196, 189, 190, 199, 155,
	86, 52, 51, 58, 145, 203, 48, 47, 205, 1,
	55, 207, 208, 149, 112, 143, 11, 26, 85, 14,
	25, 24, 8, 7, 10, 9, 19, 18, 16, 13,
	6, 23, 22, 4, 3, 2, 20, 21, 5,
}

var yyPact = [...]int16{
	9, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, 78, -1000, -1000, 161, -1000, 143, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	190, 189, 144, 142, 178, 177, 48, 81, 183, 106,
	61, 72, 47, 48, 163, 48, 157, 135, 129, 48,
	48, 128, 127, 35, -1000, -1000, -1000, 89, 34, 48,
	62, 48, 97, -1000, 141, 48, 175, 48, 32, 48,
	123, 108, 31, 29, 148, 136, -1000, 82, -1000, 80,
	48, 27, 48, 48, -16, 26, 86, 149, -1000, 25,
	119, 113, -1000, -1000, 104, 48, 48, 70, 48, 48,
	18, 48, 69, -1000, -18, -1000, 39, -1000, 16, 40,
	-1000, 48, 14, -17, -1000, 110, 107, 48, 103, -25,
	48, 67, -38, -1000, 146, 185, -1000, 48, -1000, -1000,
	-1000, 13, 79, -1000, 28, 173, 166, 12, 48, -15,
	10, 48, -24, 8, -40, 48, -1000, -1000, 48, -28,
	-1000, 48, 48, 48, 39, 154, 150, -1000, 7, 102,
	-36, -1000, -1000, -1000, 6, 66, -44, -1000, 48, 84,
	-1000, -1000, 28, -1000, 39, 39, -1000, 48, 48, -1000,
	48, 101, 48, -1000, 48, 65, -46, 48, -1000, -1000,
	-1000, 100, 63, 2, 48, -1000, 1, 48, -1000, 52,
	48, 48, -1000, -2, -1000, -3, 38, -6, -8, -1000,
	-1000, 99, -1000, -1000, 30, -9, -1000,
}

var yyPgo = [...]uint8{
	0, 228, 227, 226, 225, 224, 223, 222, 221, 220,
	219, 218, 217, 216, 215, 214, 213, 212, 211, 210,
	209, 208, 207, 206, 1, 5, 205, 204, 4, 203,
	6, 3, 2, 11, 0, 200, 199,
}

var yyR1 = [...]int8{
	0, 36, 4, 5, 5, 5, 5, 5, 5, 5,
	5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
	5, 5, 5, 5, 5, 5, 5, 5, 6, 1,
	9, 16, 17, 14, 14, 7, 7, 7, 7, 25,
	25, 24, 8, 8, 8, 8, 2, 3, 15, 23,
	20, 21, 10, 11, 26, 27, 28, 28, 29, 29,
	30, 31, 31, 31, 31, 32, 33, 12, 13, 18,
	19, 22, 34, 34, 35,
}

var yyR2 = [...]int8{
	0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 7,
	8, 15, 5, 6, 3, 7, 8, 10, 11, 1,
	3, 1, 7, 8, 10, 11, 4, 4, 4, 6,
	5, 5, 6, 5, 4, 4, 1, 3, 1, 3,
	2, 2, 3, 3, 2, 1, 1, 12, 12, 3,
	5, 3, 1, 1, 1,
}

var yyChk = [...]int16{
	-1000, -36, -4, -5, -6, -1, -9, -16, -17, -14,
	-15, -23, 11, -10, -20, 15, -11, 46, -12, -13,
	-3, -2, -7, -8, -18, -19, -22, 45, 47, 7,
	21, 22, 6, 4, 12, 13, 30, 31, 38, 16,
	20, 42, 8, 9, 16, 20, 16, 7, 7, 20,
	20, 14, 14, -34, 47, -35, 43, 32, 10, 17,
	29, 18, -34, 29, 39, 45, -34, 17, -34, 17,
	23, 23, -34, -34, 23, 23, 51, 33, 51, -34,
	39, -34, 28, 20, -34, -21, 15, -34, 51, -34,
	24, 24, 51, 51, 24, 9, 5, 24, 9, 5,
	34, 35, -34, 51, -28, -30, -32, -34, -34, 50,
	51, 33, -27, 19, 51, 25, 25, 27, -34, -34,
	40, -34, -34, 51, -34, 40, 51, 54, -33, 49,
	51, 49, -34, 51, 52, 26, 26, -34, 27, 52,
	-34, 40, 52, -26, 19, 9, -30, 51, 35, -29,
	-31, 46, 45, 44, -32, 16, 16, 51, -34, 53,
	-25, -24, -34, 51, -34, 53, -25, 51, 52, -34,
	-34, 53, 54, -32, -32, -32, -33, 17, 17, 51,
	27, 53, 54, 51, 40, 53, -28, 33, -31, -33,
	-33, -34, -34, -34, 27, -24, -34, 40, 53, -34,
	27, 40, 51, -34, 51, -34, 41, -34, -34, 51,
	51, 49, 51, 51, 27, 49, 51,
}

var yyDef = [...]int8{
	0, -2, 1, 2, 3, 4, 5, 6, 7, 8,
	9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
	19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 72, 73, 74, 0, 0, 0,
	0, 0, 0, 34, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 69, 0, 71, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 48, 0,
	0, 0, 47, 46, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 32, 0, 56, 0, 65, 0, 0,
	50, 0, 0, 0, 53, 0, 0, 0, 0, 0,
	0, 0, 0, 70, 0, 0, 33, 0, 60, 66,
	49, 0, 0, 52, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 57, 29, 0, 0,
	58, 0, 0, 0, 0, 0, 0, 35, 0, 0,
	0, 39, 41, 42, 0, 0, 0, 30, 0, 0,
	51, 55, 0, 61, 0, 0, 64, 0, 0, 36,
	0, 0, 0, 43, 0, 0, 0, 0, 59, 62,
	63, 0, 0, 0, 0, 40, 0, 0, 54, 0,
	0, 0, 37, 0, 44, 0, 0, 0, 0, 38,
	45, 0, 67, 68, 0, 0, 31,
}

var yyTok1 = [...]int8{
	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	52, 53, 3, 3, 54, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 51,
	3, 50,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 47, 48, 49,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yylex.(*lexer).node = yyDollar[1].node
		}
	case 2:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 3:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 4:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 5:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 6:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 7:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 8:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 9:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 10:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 11:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yylex.(*lexer).pass = true
			// $$ = nil
		}
	case 12:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 13:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 14:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yylex.(*lexer).pass = true
			// $$ = nil
		}
	case 15:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 16:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yylex.(*lexer).pass = true
			// $$ = nil
		}
	case 17:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 18:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 19:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 20:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 21:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 22:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 23:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 24:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 25:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 26:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yylex.(*lexer).pass = true
			// $$ = nil
		}
	case 27:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yylex.(*lexer).pass = true
			// $$ = nil
		}
	case 28:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yylex.(*lexer).pass = true
			yyVAL.node = &ast.SelectStmt{}
		}
	case 29:
		yyDollar = yyS[yypt-7 : yypt+1]
		{
			yyVAL.node = &ast.AlterSystemStmt{ConfigParameter: yyDollar[4].str, Value: yyDollar[6].str}
		}
	case 30:
		yyDollar = yyS[yypt-8 : yypt+1]
		{
			yyVAL.node = &ast.CreateDataSourceStmt{DataSourceName: yyDollar[4].str, TypeName: yyDollar[6].str, Options: yyDollar[7].optlist}
		}
	case 31:
		yyDollar = yyS[yypt-15 : yypt+1]
		{
			yyVAL.node = &ast.CreateDataMappingStmt{TypeName: yyDollar[5].str, TableName: yyDollar[8].str, ColumnName: yyDollar[10].str, Path: yyDollar[12].str, TargetIdentifier: yyDollar[14].str}
		}
	case 32:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			yyVAL.node = &ast.CreateDataOriginStmt{OriginName: yyDollar[4].str}
		}
	case 33:
		yyDollar = yyS[yypt-6 : yypt+1]
		{
			yyVAL.node = &ast.CreateUserStmt{UserName: yyDollar[3].str, Options: yyDollar[5].optlist}
		}
	case 34:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yylex.(*lexer).pass = true
		}
	case 35:
		yyDollar = yyS[yypt-7 : yypt+1]
		{
			yyVAL.node = &ast.GrantAccessOnAllStmt{UserName: yyDollar[6].str}
		}
	case 36:
		yyDollar = yyS[yypt-8 : yypt+1]
		{
			yyVAL.node = &ast.GrantAccessOnTableStmt{TableName: yyDollar[5].str, UserName: yyDollar[7].str}
		}
	case 37:
		yyDollar = yyS[yypt-10 : yypt+1]
		{
			yyVAL.node = &ast.GrantAccessOnFunctionStmt{FunctionName: yyDollar[5].str, UserName: yyDollar[9].str}
		}
	case 38:
		yyDollar = yyS[yypt-11 : yypt+1]
		{
			yyVAL.node = &ast.GrantAccessOnFunctionStmt{FunctionName: yyDollar[5].str, FunctionParameterTypes: yyDollar[7].funcparamtypelist, UserName: yyDollar[10].str}
		}
	case 39:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.funcparamtypelist = yyDollar[1].funcparamtypelist
		}
	case 40:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.funcparamtypelist = append(yyDollar[1].funcparamtypelist, yyDollar[3].funcparamtypelist...)
		}
	case 41:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.funcparamtypelist = []string{yyDollar[1].str}
		}
	case 42:
		yyDollar = yyS[yypt-7 : yypt+1]
		{
			yyVAL.node = &ast.RevokeAccessOnAllStmt{UserName: yyDollar[6].str}
		}
	case 43:
		yyDollar = yyS[yypt-8 : yypt+1]
		{
			yyVAL.node = &ast.RevokeAccessOnTableStmt{TableName: yyDollar[5].str, UserName: yyDollar[7].str}
		}
	case 44:
		yyDollar = yyS[yypt-10 : yypt+1]
		{
			yyVAL.node = &ast.RevokeAccessOnFunctionStmt{FunctionName: yyDollar[5].str, UserName: yyDollar[9].str}
		}
	case 45:
		yyDollar = yyS[yypt-11 : yypt+1]
		{
			yyVAL.node = &ast.RevokeAccessOnFunctionStmt{FunctionName: yyDollar[5].str, FunctionParameterTypes: yyDollar[7].funcparamtypelist, UserName: yyDollar[10].str}
		}
	case 46:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.node = &ast.DeregisterUserStmt{UserName: yyDollar[3].str}
		}
	case 47:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.node = &ast.RegisterUserStmt{UserName: yyDollar[3].str}
		}
	case 48:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.node = &ast.DropUserStmt{UserName: yyDollar[3].str}
		}
	case 49:
		yyDollar = yyS[yypt-6 : yypt+1]
		{
			yyVAL.node = &ast.CreateSchemaForUserStmt{UserName: yyDollar[5].str}
		}
	case 50:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			yyVAL.node = &ast.AlterTableStmt{TableName: yyDollar[3].str, Cmd: (yyDollar[4].node).(*ast.AlterTableCmd)}
		}
	case 51:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			yyVAL.node = &ast.AlterTableCmd{ColumnName: yyDollar[3].str, ColumnType: yyDollar[5].str}
		}
	case 52:
		yyDollar = yyS[yypt-6 : yypt+1]
		{
			yyVAL.node = &ast.AlterDataSourceStmt{DataSourceName: yyDollar[4].str, Options: yyDollar[5].optlist}
		}
	case 53:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			yyVAL.node = &ast.DropDataSourceStmt{DataSourceName: yyDollar[4].str}
		}
	case 54:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.optlist = yyDollar[3].optlist
		}
	case 55:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.optlist = yyDollar[3].optlist
		}
	case 56:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.optlist = yyDollar[1].optlist
		}
	case 57:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.optlist = append(yyDollar[1].optlist, yyDollar[3].optlist...)
		}
	case 58:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.optlist = yyDollar[1].optlist
		}
	case 59:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.optlist = append(yyDollar[1].optlist, yyDollar[3].optlist...)
		}
	case 60:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.optlist = []ast.Option{ast.Option{Name: yyDollar[1].str, Val: yyDollar[2].str}}
		}
	case 61:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.optlist = []ast.Option{ast.Option{Action: "DROP", Name: yyDollar[2].str, Val: ""}}
		}
	case 62:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.optlist = []ast.Option{ast.Option{Action: "SET", Name: yyDollar[2].str, Val: yyDollar[3].str}}
		}
	case 63:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.optlist = []ast.Option{ast.Option{Action: "ADD", Name: yyDollar[2].str, Val: yyDollar[3].str}}
		}
	case 64:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.optlist = []ast.Option{ast.Option{Action: "ADD", Name: yyDollar[1].str, Val: yyDollar[2].str}}
		}
	case 65:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.str = yyDollar[1].str
		}
	case 66:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.str = yyDollar[1].str
		}
	case 67:
		yyDollar = yyS[yypt-12 : yypt+1]
		{
			yyVAL.node = &ast.AuthorizeStmt{DataSourceName: yyDollar[9].str, RoleName: yyDollar[11].str}
		}
	case 68:
		yyDollar = yyS[yypt-12 : yypt+1]
		{
			yyVAL.node = &ast.DeauthorizeStmt{DataSourceName: yyDollar[9].str, RoleName: yyDollar[11].str}
		}
	case 69:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.ListStmt{Name: yyDollar[2].str}
		}
	case 70:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			yyVAL.node = &ast.RefreshInferredColumnTypesStmt{}
		}
	case 71:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.VerifyConsistencyStmt{}
		}
	case 72:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.str = yyDollar[1].str
		}
	case 73:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.str = yyDollar[1].str
		}
	}
	goto yystack /* stack new state and value */
}
