// Code generated by goyacc -l -o gram.go gram.y. DO NOT EDIT.
package parser

import __yyfmt__ "fmt"

import (
	"github.com/metadb-project/metadb/cmd/metadb/ast"
)

type yySymType struct {
	yys               int
	str               string
	funcparamtypelist []string
	optlist           []ast.Option
	node              ast.Node
	pass              bool
}

const DEREGISTER = 57346
const FUNCTION = 57347
const REGISTER = 57348
const SELECT = 57349
const SYSTEM = 57350
const TABLE = 57351
const CONSISTENCY = 57352
const CREATE = 57353
const GRANT = 57354
const REVOKE = 57355
const ACCESS = 57356
const ALTER = 57357
const DATA = 57358
const SOURCE = 57359
const ORIGIN = 57360
const OPTIONS = 57361
const USER = 57362
const AUTHORIZE = 57363
const DEAUTHORIZE = 57364
const ON = 57365
const ALL = 57366
const TABLES = 57367
const IN = 57368
const TO = 57369
const WITH = 57370
const MAPPING = 57371
const LIST = 57372
const REFRESH = 57373
const INFERRED = 57374
const COLUMN = 57375
const TYPES = 57376
const TYPE = 57377
const TRUE = 57378
const FALSE = 57379
const VERIFY = 57380
const FOR = 57381
const FROM = 57382
const PATH = 57383
const SCHEMA = 57384
const VERSION = 57385
const ADD = 57386
const SET = 57387
const DROP = 57388
const IDENT = 57389
const NUMBER = 57390
const SLITERAL = 57391

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"DEREGISTER",
	"FUNCTION",
	"REGISTER",
	"SELECT",
	"SYSTEM",
	"TABLE",
	"CONSISTENCY",
	"CREATE",
	"GRANT",
	"REVOKE",
	"ACCESS",
	"ALTER",
	"DATA",
	"SOURCE",
	"ORIGIN",
	"OPTIONS",
	"USER",
	"AUTHORIZE",
	"DEAUTHORIZE",
	"ON",
	"ALL",
	"TABLES",
	"IN",
	"TO",
	"WITH",
	"MAPPING",
	"LIST",
	"REFRESH",
	"INFERRED",
	"COLUMN",
	"TYPES",
	"TYPE",
	"TRUE",
	"FALSE",
	"VERIFY",
	"FOR",
	"FROM",
	"PATH",
	"SCHEMA",
	"VERSION",
	"ADD",
	"SET",
	"DROP",
	"IDENT",
	"NUMBER",
	"SLITERAL",
	"'='",
	"';'",
	"'('",
	"')'",
	"','",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

var yyExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 241

var yyAct = [...]uint8{
	110, 167, 132, 155, 107, 166, 108, 206, 131, 174,
	109, 192, 189, 34, 147, 33, 30, 188, 189, 57,
	12, 35, 36, 55, 15, 177, 178, 144, 228, 171,
	31, 32, 130, 57, 138, 131, 226, 55, 54, 37,
	38, 112, 63, 165, 224, 67, 223, 39, 71, 220,
	219, 74, 75, 213, 28, 18, 29, 211, 190, 186,
	210, 81, 173, 83, 169, 163, 152, 86, 137, 89,
	134, 91, 57, 158, 157, 156, 55, 127, 118, 113,
	66, 106, 96, 105, 95, 92, 111, 80, 78, 227,
	222, 117, 221, 133, 135, 64, 216, 57, 215, 122,
	123, 55, 125, 126, 40, 128, 198, 205, 41, 57,
	191, 146, 139, 55, 129, 136, 124, 90, 82, 65,
	153, 104, 142, 103, 194, 145, 114, 79, 58, 70,
	42, 60, 62, 84, 225, 209, 202, 187, 151, 77,
	143, 69, 121, 61, 164, 168, 141, 170, 168, 159,
	140, 175, 102, 172, 176, 99, 101, 120, 119, 98,
	94, 183, 182, 93, 76, 73, 72, 179, 180, 181,
	149, 100, 46, 85, 97, 51, 47, 50, 116, 193,
	185, 184, 195, 196, 197, 199, 200, 68, 201, 159,
	168, 203, 204, 43, 44, 207, 162, 161, 88, 208,
	53, 45, 52, 212, 59, 160, 214, 150, 49, 48,
	217, 218, 1, 56, 154, 115, 148, 11, 27, 87,
	14, 26, 25, 8, 7, 10, 9, 20, 19, 17,
	13, 6, 24, 23, 4, 3, 2, 21, 16, 22,
	5,
}

var yyPact = [...]int16{
	9, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, 88, -1000, -1000, 185, -1000, -1000, 156, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, 202, 201, 157, 155, 188, 186, 54, 96, 194,
	114, 66, 80, 35, 54, 170, 112, 54, 143, 142,
	54, 54, 141, 116, 37, -1000, -1000, -1000, 94, 36,
	54, 79, 54, 105, -1000, 153, 54, 183, 54, 78,
	54, 34, 139, 136, 33, 31, 150, 147, -1000, 89,
	-1000, 86, 54, 30, 54, 54, -9, 28, 93, 159,
	54, 27, -1000, 133, 132, -1000, -1000, 115, 54, 54,
	76, 54, 54, 26, 54, 74, -1000, -19, -1000, 44,
	-1000, 19, 45, -1000, 54, 17, -18, 72, -1000, 124,
	120, 54, 113, -25, 54, 71, -38, -1000, 151, 198,
	-1000, 54, -1000, -1000, -1000, 15, 85, -1000, 29, 196,
	181, 180, 14, 54, -10, 13, 54, -24, 11, -43,
	54, -1000, -1000, 54, -28, -1000, 54, 54, 54, 44,
	54, 164, 163, -1000, 8, 110, -36, -1000, -1000, -1000,
	7, 70, -42, -1000, 54, 91, -1000, -1000, 29, -1000,
	44, 44, -1000, 73, 54, 54, -1000, 54, 109, 54,
	-1000, 54, 67, -46, 54, -1000, -1000, -1000, 54, 108,
	20, 6, 54, -1000, 2, 54, -1000, 57, 55, 54,
	54, -1000, -1, -1000, -2, 43, 41, -5, -7, -1000,
	-1000, 107, -15, -1000, -1000, 40, -1000, -23, -1000,
}

var yyPgo = [...]uint8{
	0, 240, 239, 238, 237, 236, 235, 234, 233, 232,
	231, 230, 229, 228, 227, 226, 225, 224, 223, 222,
	221, 220, 219, 218, 217, 1, 5, 216, 215, 4,
	214, 6, 3, 10, 2, 0, 213, 212,
}

var yyR1 = [...]int8{
	0, 37, 5, 6, 6, 6, 6, 6, 6, 6,
	6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
	6, 6, 6, 6, 6, 6, 6, 6, 6, 7,
	1, 10, 17, 18, 15, 15, 3, 8, 8, 8,
	8, 26, 26, 25, 9, 9, 9, 9, 2, 4,
	16, 24, 21, 22, 11, 12, 27, 28, 29, 29,
	30, 30, 31, 32, 32, 32, 32, 33, 34, 13,
	14, 19, 20, 23, 35, 35, 36,
}

var yyR2 = [...]int8{
	0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	7, 8, 15, 5, 6, 3, 13, 7, 8, 10,
	11, 1, 3, 1, 7, 8, 10, 11, 4, 4,
	4, 6, 5, 5, 6, 5, 4, 4, 1, 3,
	1, 3, 2, 2, 3, 3, 2, 1, 1, 12,
	12, 3, 5, 3, 1, 1, 1,
}

var yyChk = [...]int16{
	-1000, -37, -5, -6, -7, -1, -10, -17, -18, -15,
	-16, -24, 11, -11, -21, 15, -3, -12, 46, -13,
	-14, -4, -2, -8, -9, -19, -20, -23, 45, 47,
	7, 21, 22, 6, 4, 12, 13, 30, 31, 38,
	16, 20, 42, 8, 9, 16, 16, 20, 7, 7,
	20, 20, 14, 14, -35, 47, -36, 43, 32, 10,
	17, 29, 18, -35, 29, 39, 45, -35, 17, 29,
	17, -35, 23, 23, -35, -35, 23, 23, 51, 33,
	51, -35, 39, -35, 28, 20, -35, -22, 15, -35,
	39, -35, 51, 24, 24, 51, 51, 24, 9, 5,
	24, 9, 5, 34, 35, -35, 51, -29, -31, -33,
	-35, -35, 50, 51, 33, -28, 19, -35, 51, 25,
	25, 27, -35, -35, 40, -35, -35, 51, -35, 40,
	51, 54, -34, 49, 51, 49, -35, 51, 52, 40,
	26, 26, -35, 27, 52, -35, 40, 52, -27, 19,
	9, -31, 51, 35, -30, -32, 46, 45, 44, -33,
	9, 16, 16, 51, -35, 53, -26, -25, -35, 51,
	-35, 53, -26, 51, 52, -35, -35, 53, 54, -33,
	-33, -33, -34, -35, 17, 17, 51, 27, 53, 54,
	51, 40, 53, -29, 33, -32, -34, -34, 33, -35,
	-35, -35, 27, -25, -35, 40, 53, -35, -35, 27,
	40, 51, -35, 51, -35, 41, 41, -35, -35, 51,
	51, 49, 49, 51, 51, 27, 51, 49, 51,
}

var yyDef = [...]int8{
	0, -2, 1, 2, 3, 4, 5, 6, 7, 8,
	9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
	19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
	29, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 74, 75, 76, 0, 0,
	0, 0, 0, 0, 35, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 71, 0,
	73, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 50, 0, 0, 49, 48, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 33, 0, 58, 0,
	67, 0, 0, 52, 0, 0, 0, 0, 55, 0,
	0, 0, 0, 0, 0, 0, 0, 72, 0, 0,
	34, 0, 62, 68, 51, 0, 0, 54, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 59, 30, 0, 0, 60, 0, 0, 0, 0,
	0, 0, 0, 37, 0, 0, 0, 41, 43, 44,
	0, 0, 0, 31, 0, 0, 53, 57, 0, 63,
	0, 0, 66, 0, 0, 0, 38, 0, 0, 0,
	45, 0, 0, 0, 0, 61, 64, 65, 0, 0,
	0, 0, 0, 42, 0, 0, 56, 0, 0, 0,
	0, 39, 0, 46, 0, 0, 0, 0, 0, 40,
	47, 0, 0, 69, 70, 0, 36, 0, 32,
}

var yyTok1 = [...]int8{
	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	52, 53, 3, 3, 54, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 51,
	3, 50,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 47, 48, 49,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yylex.(*lexer).node = yyDollar[1].node
		}
	case 2:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 3:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 4:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 5:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 6:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 7:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 8:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 9:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 10:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 11:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yylex.(*lexer).pass = true
			// $$ = nil
		}
	case 12:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 13:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 14:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yylex.(*lexer).pass = true
			// $$ = nil
		}
	case 15:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 16:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 17:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yylex.(*lexer).pass = true
			// $$ = nil
		}
	case 18:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 19:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 20:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 21:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 22:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 23:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 24:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 25:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 26:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 27:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yylex.(*lexer).pass = true
			// $$ = nil
		}
	case 28:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yylex.(*lexer).pass = true
			// $$ = nil
		}
	case 29:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yylex.(*lexer).pass = true
			yyVAL.node = &ast.SelectStmt{}
		}
	case 30:
		yyDollar = yyS[yypt-7 : yypt+1]
		{
			yyVAL.node = &ast.AlterSystemStmt{ConfigParameter: yyDollar[4].str, Value: yyDollar[6].str}
		}
	case 31:
		yyDollar = yyS[yypt-8 : yypt+1]
		{
			yyVAL.node = &ast.CreateDataSourceStmt{DataSourceName: yyDollar[4].str, TypeName: yyDollar[6].str, Options: yyDollar[7].optlist}
		}
	case 32:
		yyDollar = yyS[yypt-15 : yypt+1]
		{
			yyVAL.node = &ast.CreateDataMappingStmt{TypeName: yyDollar[5].str, TableName: yyDollar[8].str, ColumnName: yyDollar[10].str, Path: yyDollar[12].str, TargetIdentifier: yyDollar[14].str}
		}
	case 33:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			yyVAL.node = &ast.CreateDataOriginStmt{OriginName: yyDollar[4].str}
		}
	case 34:
		yyDollar = yyS[yypt-6 : yypt+1]
		{
			yyVAL.node = &ast.CreateUserStmt{UserName: yyDollar[3].str, Options: yyDollar[5].optlist}
		}
	case 35:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yylex.(*lexer).pass = true
		}
	case 36:
		yyDollar = yyS[yypt-13 : yypt+1]
		{
			yyVAL.node = &ast.DropDataMappingStmt{TypeName: yyDollar[5].str, TableName: yyDollar[8].str, ColumnName: yyDollar[10].str, Path: yyDollar[12].str}
		}
	case 37:
		yyDollar = yyS[yypt-7 : yypt+1]
		{
			yyVAL.node = &ast.GrantAccessOnAllStmt{UserName: yyDollar[6].str}
		}
	case 38:
		yyDollar = yyS[yypt-8 : yypt+1]
		{
			yyVAL.node = &ast.GrantAccessOnTableStmt{TableName: yyDollar[5].str, UserName: yyDollar[7].str}
		}
	case 39:
		yyDollar = yyS[yypt-10 : yypt+1]
		{
			yyVAL.node = &ast.GrantAccessOnFunctionStmt{FunctionName: yyDollar[5].str, UserName: yyDollar[9].str}
		}
	case 40:
		yyDollar = yyS[yypt-11 : yypt+1]
		{
			yyVAL.node = &ast.GrantAccessOnFunctionStmt{FunctionName: yyDollar[5].str, FunctionParameterTypes: yyDollar[7].funcparamtypelist, UserName: yyDollar[10].str}
		}
	case 41:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.funcparamtypelist = yyDollar[1].funcparamtypelist
		}
	case 42:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.funcparamtypelist = append(yyDollar[1].funcparamtypelist, yyDollar[3].funcparamtypelist...)
		}
	case 43:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.funcparamtypelist = []string{yyDollar[1].str}
		}
	case 44:
		yyDollar = yyS[yypt-7 : yypt+1]
		{
			yyVAL.node = &ast.RevokeAccessOnAllStmt{UserName: yyDollar[6].str}
		}
	case 45:
		yyDollar = yyS[yypt-8 : yypt+1]
		{
			yyVAL.node = &ast.RevokeAccessOnTableStmt{TableName: yyDollar[5].str, UserName: yyDollar[7].str}
		}
	case 46:
		yyDollar = yyS[yypt-10 : yypt+1]
		{
			yyVAL.node = &ast.RevokeAccessOnFunctionStmt{FunctionName: yyDollar[5].str, UserName: yyDollar[9].str}
		}
	case 47:
		yyDollar = yyS[yypt-11 : yypt+1]
		{
			yyVAL.node = &ast.RevokeAccessOnFunctionStmt{FunctionName: yyDollar[5].str, FunctionParameterTypes: yyDollar[7].funcparamtypelist, UserName: yyDollar[10].str}
		}
	case 48:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.node = &ast.DeregisterUserStmt{UserName: yyDollar[3].str}
		}
	case 49:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.node = &ast.RegisterUserStmt{UserName: yyDollar[3].str}
		}
	case 50:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.node = &ast.DropUserStmt{UserName: yyDollar[3].str}
		}
	case 51:
		yyDollar = yyS[yypt-6 : yypt+1]
		{
			yyVAL.node = &ast.CreateSchemaForUserStmt{UserName: yyDollar[5].str}
		}
	case 52:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			yyVAL.node = &ast.AlterTableStmt{TableName: yyDollar[3].str, Cmd: (yyDollar[4].node).(*ast.AlterTableCmd)}
		}
	case 53:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			yyVAL.node = &ast.AlterTableCmd{ColumnName: yyDollar[3].str, ColumnType: yyDollar[5].str}
		}
	case 54:
		yyDollar = yyS[yypt-6 : yypt+1]
		{
			yyVAL.node = &ast.AlterDataSourceStmt{DataSourceName: yyDollar[4].str, Options: yyDollar[5].optlist}
		}
	case 55:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			yyVAL.node = &ast.DropDataSourceStmt{DataSourceName: yyDollar[4].str}
		}
	case 56:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.optlist = yyDollar[3].optlist
		}
	case 57:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.optlist = yyDollar[3].optlist
		}
	case 58:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.optlist = yyDollar[1].optlist
		}
	case 59:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.optlist = append(yyDollar[1].optlist, yyDollar[3].optlist...)
		}
	case 60:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.optlist = yyDollar[1].optlist
		}
	case 61:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.optlist = append(yyDollar[1].optlist, yyDollar[3].optlist...)
		}
	case 62:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.optlist = []ast.Option{ast.Option{Name: yyDollar[1].str, Val: yyDollar[2].str}}
		}
	case 63:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.optlist = []ast.Option{ast.Option{Action: "DROP", Name: yyDollar[2].str, Val: ""}}
		}
	case 64:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.optlist = []ast.Option{ast.Option{Action: "SET", Name: yyDollar[2].str, Val: yyDollar[3].str}}
		}
	case 65:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.optlist = []ast.Option{ast.Option{Action: "ADD", Name: yyDollar[2].str, Val: yyDollar[3].str}}
		}
	case 66:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.optlist = []ast.Option{ast.Option{Action: "ADD", Name: yyDollar[1].str, Val: yyDollar[2].str}}
		}
	case 67:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.str = yyDollar[1].str
		}
	case 68:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.str = yyDollar[1].str
		}
	case 69:
		yyDollar = yyS[yypt-12 : yypt+1]
		{
			yyVAL.node = &ast.AuthorizeStmt{DataSourceName: yyDollar[9].str, RoleName: yyDollar[11].str}
		}
	case 70:
		yyDollar = yyS[yypt-12 : yypt+1]
		{
			yyVAL.node = &ast.DeauthorizeStmt{DataSourceName: yyDollar[9].str, RoleName: yyDollar[11].str}
		}
	case 71:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.ListStmt{Name: yyDollar[2].str}
		}
	case 72:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			yyVAL.node = &ast.RefreshInferredColumnTypesStmt{}
		}
	case 73:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.VerifyConsistencyStmt{}
		}
	case 74:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.str = yyDollar[1].str
		}
	case 75:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.str = yyDollar[1].str
		}
	}
	goto yystack /* stack new state and value */
}
